"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _icons = require("../icons");

var _icons2 = _interopRequireDefault(_icons);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

exports.default = [{ type: "inline", label: "B", style: "BOLD", icon: _icons2.default.BoldIcon }, { type: "inline", label: "I", style: "ITALIC", icon: _icons2.default.ItalicIcon }, { type: "inline", label: "U", style: "UNDERLINE", icon: _icons2.default.UnderlineIcon }, { type: "inline", label: "S", style: "STRIKETHROUGH", icon: _icons2.default.StrikeThroughIcon }, { type: "entity", label: "Link", style: "link", entity: "LINK", icon: _icons2.default.LinkIcon }, { type: "inline", label: "CI", style: "CODE", icon: _icons2.default.CodeInlineIcon }, { type: "separator" }, { type: "block", label: "UL", style: "unordered-list-item", icon: _icons2.default.ULIcon }, { type: "block", label: "OL", style: "ordered-list-item", icon: _icons2.default.OLIcon }, { type: "block", label: "H3", style: "header-three", icon: _icons2.default.H3Icon }, { type: "block", label: "H4", style: "header-four", icon: _icons2.default.H4Icon }, { type: "block", label: "QT", style: "blockquote", icon: _icons2.default.BlockQuoteIcon }, { type: "block", label: "CB", style: "code-block", icon: _icons2.default.CodeBlockIcon }]; /*
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    * Copyright (c) 2016, Globo.com (https://github.com/globocom)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    * License: MIT
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    */